#!/bin/bash
mkdir ./output
make -j4
rm -rf output/*
mkdir ./output/modules
cp ./arch/arm/boot/zImage ./output/boot.img-zImage
find ! -path './output*' ! -path './cwm-zip*' ! -path './blackhawk-tools*' -name "*.ko" -exec cp {} ./output/modules/ \;
mv ./output/modules/reset_modem.ko ./blackhawk-tools/unpack/boot.img-ramdisk/lib/modules
cp ./output/boot.img-zImage ./blackhawk-tools/unpack/boot.img-zImage
cd blackhawk-tools
./repackbootimg.sh boot.img

cd ..
cp ./blackhawk-tools/boot.img-repack ./output/boot.img
cp ./output/boot.img cwm-zip/boot.img
rm cwm-zip/system/lib/modules/*
cp ./output/modules/* cwm-zip/system/lib/modules
cd cwm-zip
zip -r -0 newkernel.zip ./* 
adb push newkernel.zip /sdcard/
adb reboot recovery
